---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
      - name: frontend
        image: anchu72docker/ecomm:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: ecommerce-frontend
  ports:
  - port: 80
    targetPort: 80

...
